=== navikt/ekspertbistand/backend/src/main/resources/dokumentmaler/templates/vedtakArbeidsgiverInnvilget/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Vedtaksbrev på foreløpig vedtak",
  "type": "object",
  "properties": {
    "dato": {
      "type": "string"
    },
    "deltaker": {
      "type": "object",
      "properties": {
        "navn": {
          "type": "string"
        }
      },
      "required": [
        "navn"
      ]
    },
    "arbeidsgiver": {
      "type": "object",
      "properties": {
        "navn": {
          "type": "string"
        },
        "orgnr": {
          "type": "string"
        }
      },
      "required": [
        "navn",
        "orgnr"
      ]
    },
    "soknadssum": {
      "type": [
        "string",
        "null"
      ]
    },
    "innvilgetBelop": {
      "type": [
        "string",
        "null"
      ]
    },
    "tiltaksperiode": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "fra": {
          "type": "string"
        },
        "til": {
          "type": "string"
        }
      }
    },
    "refusjonsfrist": {
      "type": [
        "string",
        "null"
      ]
    },
    "begrunnelse": {
      "type": [
        "string",
        "null"
      ]
    },
    "navEnhet": {
      "type": [
        "string",
        "null"
      ]
    },
    "saksbehandler": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "required": [
    "dato",
    "deltaker",
    "arbeidsgiver",
    "soknadssum",
    "innvilgetBelop",
    "tiltaksperiode",
    "refusjonsfrist",
    "begrunnelse",
    "navEnhet",
    "saksbehandler"
  ]
}

=== navikt/ekspertbistand/backend/src/main/resources/dokumentmaler/templates/vedtakDeltakerAvslag/testdata/uten-enhet-og-saksbehandler.json
{
  "dato": "13. oktober 2026",
  "deltaker": {
    "navn": "Ola Testdeltaker"
  },
  "arbeidsgiver": {
    "navn": "Eksempel Bedrift AS",
    "orgnr": "123456780"
  },
  "soknadssum": "22 000",
  "innvilgetBelop": null,
  "tiltaksperiode": null,
  "refusjonsfrist": null,
  "begrunnelse": "Ekspertbistand kan hjelpe deg tilbake i arbeid.\nVi har lagt vekt på det du og arbeidsgiveren din har beskrevet.",
  "navEnhet": null,
  "saksbehandler": null
}

=== navikt/ekspertbistand/backend/src/main/resources/dokumentmaler/templates/vedtakArbeidsgiverAvslag/testdata/default.json
{
  "dato": "13. oktober 2026",
  "deltaker": {
    "navn": "Ola Testdeltaker"
  },
  "arbeidsgiver": {
    "navn": "Eksempel Bedrift AS",
    "orgnr": "123456780"
  },
  "soknadssum": "22 000",
  "innvilgetBelop": null,
  "tiltaksperiode": null,
  "refusjonsfrist": null,
  "begrunnelse": "Vilkårene for tilskudd er ikke oppfylt.",
  "navEnhet": "Nav Testenhet",
  "saksbehandler": "Siri Saksbehandler"
}

=== navikt/ekspertbistand/backend/src/main/resources/dokumentmaler/templates/vedtakArbeidsgiverInnvilgetRedusert/testdata/default.json
{
  "dato": "13. oktober 2026",
  "deltaker": {
    "navn": "Ola Testdeltaker"
  },
  "arbeidsgiver": {
    "navn": "Eksempel Bedrift AS",
    "orgnr": "123456780"
  },
  "soknadssum": "22 000",
  "innvilgetBelop": "15 000",
  "tiltaksperiode": {
    "fra": "22. november 2026",
    "til": "31. desember 2026"
  },
  "refusjonsfrist": "30. juni 2027",
  "begrunnelse": "Søknadssummen er over maks sats.\nVi har derfor innvilget et lavere beløp.",
  "navEnhet": "Nav Testenhet",
  "saksbehandler": "Siri Saksbehandler"
}

=== navikt/ekspertbistand/backend/src/main/resources/dokumentmaler/templates/vedtakDeltakerInnvilget/testdata/uten-enhet-og-saksbehandler.json
{
  "dato": "13. oktober 2026",
  "deltaker": {
    "navn": "Ola Testdeltaker"
  },
  "arbeidsgiver": {
    "navn": "Eksempel Bedrift AS",
    "orgnr": "123456780"
  },
  "soknadssum": "22 000",
  "innvilgetBelop": "22 000",
  "tiltaksperiode": {
    "fra": "22. november 2026",
    "til": "31. desember 2026"
  },
  "refusjonsfrist": "30. juni 2027",
  "begrunnelse": "Ekspertbistand kan hjelpe deg tilbake i arbeid.\nVi har lagt vekt på det du og arbeidsgiveren din har beskrevet.",
  "navEnhet": null,
  "saksbehandler": null
}

=== navikt/ekspertbistand/backend/src/main/resources/dokumentmaler/templates/vedtakArbeidsgiverInnvilget/testdata/default.json
{
  "dato": "13. oktober 2026",
  "deltaker": {
    "navn": "Ola Testdeltaker"
  },
  "arbeidsgiver": {
    "navn": "Eksempel Bedrift AS",
    "orgnr": "123456780"
  },
  "soknadssum": "22 000",
  "innvilgetBelop": "22 000",
  "tiltaksperiode": {
    "fra": "22. november 2026",
    "til": "31. desember 2026"
  },
  "refusjonsfrist": "30. juni 2027",
  "begrunnelse": null,
  "navEnhet": "Nav Testenhet",
  "saksbehandler": "Siri Saksbehandler"
}
